"""
Run once to seed the PostgreSQL database with COMPLETE syllabus data.
Usage (from backend/ directory, venv active):
    python -m app.syllabus_seed
"""
from app.database import SessionLocal, engine, Base
from app.models import Subject, SyllabusModule, Topic

DSA_DATA = {
    "title": "Data Structures & Algorithms", "tag": "CS301", "progress": 0.65, "next_module": "Binary Search Trees",
    "modules": [
        {"title": "Arrays & Strings", "order": 0, "completed": 1, "topics": [
            {"title": "What is an Array?", "theory": "An array is a collection of elements stored at contiguous memory locations. Arrays provide O(1) random access and O(n) insertion/deletion at arbitrary positions.", "video_url": "https://www.youtube.com/watch?v=QJNwK2uJyGs", "doc_url": "https://www.geeksforgeeks.org/array-data-structure/", "code_example": "arr = [10, 20, 30, 40, 50]\nprint(arr[0])     # O(1) access\narr.append(60)    # O(1) amortized\narr.insert(2, 99) # O(n) — shifts elements", "practice_task": "Reverse an array in-place without using extra memory."},
            {"title": "Two Pointers Technique", "theory": "Two pointers is a pattern where two indices traverse the array — often from opposite ends. Used in sorted-array problems, pair-sum, and palindrome checks. Time: O(n), Space: O(1).", "video_url": "https://www.youtube.com/watch?v=On03HWe2tZM", "doc_url": "https://www.geeksforgeeks.org/two-pointers-technique/", "code_example": "def two_sum_sorted(arr, target):\n    left, right = 0, len(arr) - 1\n    while left < right:\n        s = arr[left] + arr[right]\n        if s == target: return (left, right)\n        elif s < target: left += 1\n        else: right -= 1\n    return None", "practice_task": "Given a sorted array, find all pairs that sum to a target value using the two-pointer technique."},
            {"title": "Sliding Window", "theory": "The sliding window pattern maintains a 'window' (subarray) that slides over the data. Avoids nested loops for subarray problems, reducing O(n²) → O(n).", "video_url": "https://www.youtube.com/watch?v=p-ss2JNynmw", "doc_url": "https://www.geeksforgeeks.org/window-sliding-technique/", "code_example": "def max_sum_subarray(arr, k):\n    window = sum(arr[:k])\n    best = window\n    for i in range(k, len(arr)):\n        window += arr[i] - arr[i - k]\n        best = max(best, window)\n    return best", "practice_task": "Find the longest substring with at most K distinct characters using a sliding window."},
            {"title": "String Manipulation", "theory": "Strings are immutable sequences of characters. Key patterns: slicing, hashing for anagram detection, and KMP for pattern matching.", "video_url": "https://www.youtube.com/watch?v=ThjvMReOXYM", "doc_url": "https://docs.python.org/3/library/stdtypes.html#text-sequence-type-str", "code_example": "from collections import Counter\ndef is_anagram(s, t):\n    return Counter(s) == Counter(t)\n\nprint(is_anagram('listen', 'silent'))  # True", "practice_task": "Implement a function to find all anagram substrings of pattern p in string s. Return their starting indices."},
        ]},
        {"title": "Linked Lists & Pointers", "order": 1, "completed": 1, "topics": [
            {"title": "Singly Linked Lists", "theory": "A singly linked list stores data in nodes where each node points to the next. Unlike arrays, no contiguous memory is required. Insertion at head: O(1). Access: O(n).", "video_url": "https://www.youtube.com/watch?v=F8AbOfQwl1c", "doc_url": "https://www.geeksforgeeks.org/data-structures/linked-list/", "code_example": "class Node:\n    def __init__(self, data):\n        self.data = data\n        self.next = None\n\nclass LinkedList:\n    def __init__(self): self.head = None\n    def append(self, data):\n        node = Node(data)\n        if not self.head: self.head = node; return\n        cur = self.head\n        while cur.next: cur = cur.next\n        cur.next = node", "practice_task": "Implement a function to reverse a singly linked list iteratively in O(n) time, O(1) space."},
            {"title": "Doubly Linked Lists", "theory": "Each node has pointers to both next and previous nodes. Allows O(1) insertion/deletion at both ends. Used internally by Python's collections.deque.", "video_url": "https://www.youtube.com/watch?v=e9NG_a2Z0e8", "doc_url": "https://www.geeksforgeeks.org/doubly-linked-list/", "code_example": "class DNode:\n    def __init__(self, data):\n        self.data = data\n        self.next = None\n        self.prev = None\n\n# Insert after a given node\ndef insert_after(node, data):\n    new = DNode(data)\n    new.next = node.next\n    new.prev = node\n    if node.next: node.next.prev = new\n    node.next = new", "practice_task": "Implement an LRU Cache using a doubly linked list + hash map with O(1) get and put operations."},
            {"title": "Cycle Detection (Floyd's Algorithm)", "theory": "Floyd's Tortoise and Hare uses two pointers moving at different speeds to detect cycles. If they meet, a cycle exists. Time: O(n), Space: O(1).", "video_url": "https://www.youtube.com/watch?v=gBTe7lFR3vc", "doc_url": "https://www.geeksforgeeks.org/floyds-cycle-detection-algorithm/", "code_example": "def has_cycle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n        if slow == fast:\n            return True\n    return False", "practice_task": "Find the starting node of a cycle in a linked list (not just whether one exists)."},
        ]},
        {"title": "Stacks and Queues", "order": 2, "completed": 1, "topics": [
            {"title": "Stack — LIFO", "theory": "A stack follows Last-In-First-Out order. Used for undo operations, function call stacks, DFS, and expression evaluation. All operations O(1).", "video_url": "https://www.youtube.com/watch?v=KcT3aVgrrpU", "doc_url": "https://www.geeksforgeeks.org/stack-data-structure/", "code_example": "stack = []\nstack.append(1)   # push\nstack.append(2)\nstack.append(3)\nprint(stack.pop())  # 3 — LIFO\nprint(stack[-1])    # 2 — peek", "practice_task": "Using a stack, evaluate an arithmetic expression in Reverse Polish Notation (e.g., '2 1 + 3 *' = 9)."},
            {"title": "Queue — FIFO", "theory": "A queue follows First-In-First-Out order. Used for BFS, scheduling, and streaming. Use collections.deque for O(1) operations at both ends.", "video_url": "https://www.youtube.com/watch?v=D6gu-_tmEpQ", "doc_url": "https://docs.python.org/3/library/collections.html#collections.deque", "code_example": "from collections import deque\nq = deque()\nq.append('a')      # enqueue\nq.append('b')\nq.append('c')\nprint(q.popleft()) # 'a' — FIFO", "practice_task": "implement BFS on a grid to find the shortest path from start to end, treating '0' as open and '1' as wall."},
            {"title": "Monotonic Stack", "theory": "A monotonic stack maintains elements in sorted order. Used for Next Greater Element, Daily Temperatures, and histogram problems. Reduces O(n²) brute force to O(n).", "video_url": "https://www.youtube.com/watch?v=Dq_ObZwTY_Q", "doc_url": "https://www.geeksforgeeks.org/introduction-to-monotonic-stack/", "code_example": "def next_greater(arr):\n    result = [-1] * len(arr)\n    stack = []  # stores indices\n    for i, val in enumerate(arr):\n        while stack and arr[stack[-1]] < val:\n            result[stack.pop()] = val\n        stack.append(i)\n    return result\n\nprint(next_greater([4, 5, 2, 10]))  # [5, 10, 10, -1]", "practice_task": "Solve the 'Daily Temperatures' problem: given temperatures, return how many days until a warmer temperature."},
        ]},
        {"title": "Hash Tables", "order": 3, "completed": 1, "topics": [
            {"title": "Hash Functions & Collisions", "theory": "A hash function maps keys to array indices. Collisions occur when two keys map to the same index. Resolved via chaining (linked lists) or open addressing (linear probing).", "video_url": "https://www.youtube.com/watch?v=KyUTuwz_b7Q", "doc_url": "https://www.geeksforgeeks.org/hashing-data-structure/", "code_example": "# Python dict is a hash map\nfreq = {}\nfor char in 'hello world':\n    freq[char] = freq.get(char, 0) + 1\nprint(freq)", "practice_task": "Implement a basic hash map from scratch using an array of linked lists to handle collisions."},
            {"title": "HashMap vs HashSet", "theory": "HashMap (dict) stores key-value pairs. HashSet (set) stores unique keys only. Both offer O(1) average lookup. Use sets for membership testing, dicts for counting/mapping.", "video_url": "https://www.youtube.com/watch?v=shs0KM3wKv8", "doc_url": "https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset", "code_example": "# HashSet for duplicate detection\nnums = [1, 2, 3, 1, 4]\nseen = set()\nfor n in nums:\n    if n in seen:\n        print(f'Duplicate: {n}')\n    else:\n        seen.add(n)", "practice_task": "Given an array of integers, find all pairs that sum to zero using a hash set in O(n) time."},
        ]},
        {"title": "Binary Search Trees", "order": 4, "completed": 0, "topics": [
            {"title": "BST Fundamentals", "theory": "A Binary Search Tree is a node-based binary tree where left subtree values < parent < right subtree values. Average O(log n) for search/insert/delete; O(n) worst case for skewed trees.", "video_url": "https://www.youtube.com/watch?v=pYT9F8_LFTM", "doc_url": "https://www.geeksforgeeks.org/binary-search-tree-data-structure/", "code_example": "class BSTNode:\n    def __init__(self, key):\n        self.key = key\n        self.left = self.right = None\n\ndef insert(root, key):\n    if not root: return BSTNode(key)\n    if key < root.key: root.left = insert(root.left, key)\n    else: root.right = insert(root.right, key)\n    return root", "practice_task": "Find the Lowest Common Ancestor (LCA) of two nodes in a BST in O(log n) time."},
            {"title": "BST Traversals", "theory": "Three depth-first traversals: Inorder (Left→Root→Right) gives sorted output. Preorder (Root→Left→Right) for tree serialization. Postorder (Left→Right→Root) for deletion.", "video_url": "https://www.youtube.com/watch?v=BHB0B1jFKQc", "doc_url": "https://www.geeksforgeeks.org/tree-traversals-inorder-preorder-and-postorder/", "code_example": "def inorder(root):\n    if root:\n        inorder(root.left)\n        print(root.key, end=' ')\n        inorder(root.right)\n\ndef level_order(root):\n    from collections import deque\n    q = deque([root])\n    while q:\n        node = q.popleft()\n        print(node.key, end=' ')\n        if node.left: q.append(node.left)\n        if node.right: q.append(node.right)", "practice_task": "Serialize a BST to a string and deserialize it back to the original tree structure."},
            {"title": "AVL Trees (Self-Balancing)", "theory": "AVL trees maintain balance by tracking height differences (balance factor = -1, 0, or 1). Perform rotations (LL, RR, LR, RL) on insertion/deletion to restore balance. Guarantees O(log n) always.", "video_url": "https://www.youtube.com/watch?v=jDM6_TnYIqE", "doc_url": "https://www.geeksforgeeks.org/avl-tree-set-1-insertion/", "code_example": "def get_height(node):\n    return node.height if node else 0\n\ndef get_balance(node):\n    return get_height(node.left) - get_height(node.right) if node else 0\n\ndef right_rotate(y):\n    x = y.left\n    T2 = x.right\n    x.right = y\n    y.left = T2\n    y.height = 1 + max(get_height(y.left), get_height(y.right))\n    x.height = 1 + max(get_height(x.left), get_height(x.right))\n    return x", "practice_task": "Insert nodes [10, 20, 30, 40, 50] into an AVL tree one by one, drawing the rotations that occur at each step."},
        ]},
        {"title": "Graph Traversal (BFS & DFS)", "order": 5, "completed": 0, "topics": [
            {"title": "Graph Representations", "theory": "Graphs can be represented as:\n1. Adjacency Matrix — 2D array, O(V²) space, O(1) edge lookup\n2. Adjacency List — list of lists, O(V+E) space, best for sparse graphs\n3. Edge List — list of (u,v) tuples, used in Kruskal's algorithm", "video_url": "https://www.youtube.com/watch?v=c8P9kB-ixRk", "doc_url": "https://www.geeksforgeeks.org/graph-and-its-representations/", "code_example": "# Adjacency List (most common)\ngraph = {\n    0: [1, 2],\n    1: [0, 3],\n    2: [0, 4],\n    3: [1],\n    4: [2]\n}", "practice_task": "Convert an edge list [(0,1),(1,2),(2,3)] into both an adjacency matrix and adjacency list representation."},
            {"title": "BFS — Breadth First Search", "theory": "BFS explores all neighbors at the current depth before going deeper. Uses a queue. Time/Space: O(V+E). Used for shortest path on unweighted graphs, level-order traversal.", "video_url": "https://www.youtube.com/watch?v=oDqjPvD1SsI", "doc_url": "https://www.geeksforgeeks.org/breadth-first-search-or-bfs-for-a-graph/", "code_example": "from collections import deque\n\ndef bfs(graph, start):\n    visited = set([start])\n    queue = deque([start])\n    while queue:\n        node = queue.popleft()\n        print(node, end=' ')\n        for neighbor in graph[node]:\n            if neighbor not in visited:\n                visited.add(neighbor)\n                queue.append(neighbor)", "practice_task": "Find the shortest path between two nodes in an unweighted graph using BFS. Return the path as a list."},
            {"title": "DFS — Depth First Search", "theory": "DFS explores as far as possible down each branch before backtracking. Uses a stack (or recursion). Time: O(V+E). Used for cycle detection, topological sort, and connected components.", "video_url": "https://www.youtube.com/watch?v=Urx87-NMm6c", "doc_url": "https://www.geeksforgeeks.org/depth-first-search-or-dfs-for-a-graph/", "code_example": "def dfs(graph, node, visited=None):\n    if visited is None: visited = set()\n    visited.add(node)\n    print(node, end=' ')\n    for neighbor in graph[node]:\n        if neighbor not in visited:\n            dfs(graph, neighbor, visited)\n    return visited", "practice_task": "Detect if a directed graph has a cycle using DFS. Return True if a cycle exists, False otherwise."},
        ]},
        {"title": "Dynamic Programming", "order": 6, "completed": 0, "topics": [
            {"title": "Introduction to DP", "theory": "Dynamic Programming solves problems by breaking them into overlapping subproblems and storing their results (memoization/tabulation). Key insight: optimal substructure + overlapping subproblems.", "video_url": "https://www.youtube.com/watch?v=oBt53YbR9Kk", "doc_url": "https://www.geeksforgeeks.org/dynamic-programming/", "code_example": "# Fibonacci — naive O(2^n)\ndef fib_naive(n):\n    if n <= 1: return n\n    return fib_naive(n-1) + fib_naive(n-2)\n\n# Fibonacci — memoization O(n)\nfrom functools import lru_cache\n@lru_cache(maxsize=None)\ndef fib(n):\n    if n <= 1: return n\n    return fib(n-1) + fib(n-2)", "practice_task": "Solve the 0/1 Knapsack problem using dynamic programming (tabulation). Given weights, values, and capacity — maximize total value."},
            {"title": "Tabulation (Bottom-Up DP)", "theory": "Instead of recursion with memoization, tabulation builds solutions iteratively from base cases up. Avoids stack overflow. Same O(n) time but often faster in practice due to no function call overhead.", "video_url": "https://www.youtube.com/watch?v=tgVSkMA8joQ", "doc_url": "https://www.geeksforgeeks.org/tabulation-vs-memoization/", "code_example": "def climb_stairs(n):\n    if n <= 2: return n\n    dp = [0] * (n + 1)\n    dp[1], dp[2] = 1, 2\n    for i in range(3, n + 1):\n        dp[i] = dp[i-1] + dp[i-2]\n    return dp[n]\n\nprint(climb_stairs(5))  # 8", "practice_task": "Solve Longest Common Subsequence (LCS) of two strings using a 2D DP table. Return both the length and the actual subsequence."},
            {"title": "Classic DP — Coin Change & LCS", "theory": "Coin Change: minimum coins to make amount. LCS: longest subsequence common to two strings. Both are foundational DP patterns that appear frequently in interviews.", "video_url": "https://www.youtube.com/watch?v=H9bfqozjoqs", "doc_url": "https://leetcode.com/problems/coin-change/", "code_example": "def coin_change(coins, amount):\n    dp = [float('inf')] * (amount + 1)\n    dp[0] = 0\n    for coin in coins:\n        for x in range(coin, amount + 1):\n            dp[x] = min(dp[x], dp[x - coin] + 1)\n    return dp[amount] if dp[amount] != float('inf') else -1\n\nprint(coin_change([1, 5, 11], 15))  # 2", "practice_task": "Solve the 'Edit Distance' problem: find the minimum number of insert/delete/replace operations to convert string A to string B."},
        ]},
    ]
}

AI_DATA = {
    "title": "Artificial Intelligence", "tag": "CS405", "progress": 0.40, "next_module": "Neural Networks Basics",
    "modules": [
        {"title": "Introduction to AI", "order": 0, "completed": 1, "topics": [
            {"title": "What is Artificial Intelligence?", "theory": "AI refers to the simulation of human intelligence in machines. Key subfields: Machine Learning (data-driven models), Deep Learning (neural networks), NLP (text/language), Computer Vision.", "video_url": "https://www.youtube.com/watch?v=ad79nYk2keg", "doc_url": "https://ai.google/education/", "code_example": "# Rule-based AI example\ndef smart_thermostat(temperature):\n    if temperature < 18: return 'Heating ON'\n    elif temperature > 26: return 'Cooling ON'\n    else: return 'System IDLE'\nprint(smart_thermostat(15))", "practice_task": "Research the Turing Test and write a 200-word summary: is it a good measure of machine intelligence? Why or why not?"},
            {"title": "History & Types of AI", "theory": "AI history: Turing (1950) → Expert Systems (1970s) → ML boom (1990s) → Deep Learning revolution (2012+).\nTypes: Narrow AI (specialized tasks), General AI (human-level, theoretical), Super AI (beyond human, hypothetical).", "video_url": "https://www.youtube.com/watch?v=mJeNghZXtMo", "doc_url": "https://www.ibm.com/cloud/learn/what-is-artificial-intelligence", "code_example": "# Narrow AI: image classifier\nfrom sklearn.datasets import load_iris\nfrom sklearn.tree import DecisionTreeClassifier\n\niris = load_iris()\nclf = DecisionTreeClassifier()\nclf.fit(iris.data, iris.target)\nprint(clf.predict([[5.1, 3.5, 1.4, 0.2]]))  # [0]", "practice_task": "Create a timeline of 10 key milestones in AI history from 1950 to today, explaining the significance of each."},
        ]},
        {"title": "Search Algorithms (A*)", "order": 1, "completed": 1, "topics": [
            {"title": "Uninformed Search (BFS, DFS)", "theory": "Uninformed search has no domain knowledge. BFS finds shortest path (unweighted), DFS uses less memory but may not find optimal. Neither uses heuristics.", "video_url": "https://www.youtube.com/watch?v=TIbzvgZpnSk", "doc_url": "https://www.geeksforgeeks.org/uninformed-search-algorithms-in-ai/", "code_example": "# BFS for pathfinding\nfrom collections import deque\ndef bfs_path(graph, start, goal):\n    q = deque([[start]])\n    visited = {start}\n    while q:\n        path = q.popleft()\n        node = path[-1]\n        if node == goal: return path\n        for n in graph.get(node, []):\n            if n not in visited:\n                visited.add(n)\n                q.append(path + [n])", "practice_task": "Implement BFS and DFS to solve a maze. Compare the paths they find and explain the trade-offs."},
            {"title": "A* Search Algorithm", "theory": "A* uses f(n) = g(n) + h(n) where g(n) = cost from start, h(n) = heuristic estimate to goal. Finds optimal path if h(n) is admissible (never overestimates). Most efficient informed search.", "video_url": "https://www.youtube.com/watch?v=JtiK0DOeI4A", "doc_url": "https://www.geeksforgeeks.org/a-search-algorithm/", "code_example": "import heapq\n\ndef astar(graph, h, start, goal):\n    pq = [(h[start], 0, start, [start])]\n    visited = set()\n    while pq:\n        f, g, node, path = heapq.heappop(pq)\n        if node == goal: return path\n        if node in visited: continue\n        visited.add(node)\n        for neighbor, cost in graph[node]:\n            if neighbor not in visited:\n                ng = g + cost\n                heapq.heappush(pq, (ng + h[neighbor], ng, neighbor, path + [neighbor]))", "practice_task": "Use A* with Manhattan distance heuristic to solve the 8-puzzle problem (3x3 grid). Print the solution steps."},
        ]},
        {"title": "Game Playing (Minimax)", "order": 2, "completed": 1, "topics": [
            {"title": "Minimax Algorithm", "theory": "Minimax is used for two-player zero-sum games. MAX player maximizes score; MIN player minimizes it. Explores the entire game tree to find the optimal move. Time: O(b^d) where b=branching factor, d=depth.", "video_url": "https://www.youtube.com/watch?v=l-hh51ncgDI", "doc_url": "https://www.geeksforgeeks.org/minimax-algorithm-in-game-theory-set-1-introduction/", "code_example": "def minimax(board, depth, is_max):\n    score = evaluate(board)\n    if score == 10 or score == -10 or is_full(board):\n        return score\n    if is_max:\n        best = -1000\n        for move in get_moves(board):\n            apply(board, move, 'X')\n            best = max(best, minimax(board, depth+1, False))\n            undo(board, move)\n        return best\n    else:\n        best = 1000\n        for move in get_moves(board):\n            apply(board, move, 'O')\n            best = min(best, minimax(board, depth+1, True))\n            undo(board, move)\n        return best", "practice_task": "Implement a Tic-Tac-Toe AI using Minimax. The AI should never lose."},
            {"title": "Alpha-Beta Pruning", "theory": "Alpha-Beta pruning optimizes Minimax by eliminating branches that cannot affect the final decision. Reduces time complexity from O(b^d) to O(b^(d/2)) in the best case — doubling the search depth.", "video_url": "https://www.youtube.com/watch?v=xBXHtz4Gbdo", "doc_url": "https://www.geeksforgeeks.org/minimax-algorithm-in-game-theory-set-4-alpha-beta-pruning/", "code_example": "def alphabeta(node, depth, alpha, beta, is_max):\n    if depth == 0: return evaluate(node)\n    if is_max:\n        val = float('-inf')\n        for child in node.children:\n            val = max(val, alphabeta(child, depth-1, alpha, beta, False))\n            alpha = max(alpha, val)\n            if beta <= alpha: break  # beta cutoff\n        return val\n    else:\n        val = float('inf')\n        for child in node.children:\n            val = min(val, alphabeta(child, depth-1, alpha, beta, True))\n            beta = min(beta, val)\n            if beta <= alpha: break  # alpha cutoff\n        return val", "practice_task": "Add Alpha-Beta pruning to your Tic-Tac-Toe Minimax implementation and count how many fewer nodes are evaluated compared to plain Minimax."},
        ]},
        {"title": "Neural Networks Basics", "order": 3, "completed": 0, "topics": [
            {"title": "Perceptrons & Activation Functions", "theory": "A neural network is composed of neurons computing weighted sums passed through activation functions.\nReLU: max(0,x) — avoids vanishing gradient\nSigmoid: 1/(1+e^-x) — outputs (0,1)\nSoftmax: multi-class output probabilities", "video_url": "https://www.youtube.com/watch?v=aircAruvnKk", "doc_url": "https://developers.google.com/machine-learning/crash-course/introduction-to-neural-networks", "code_example": "import numpy as np\n\ndef relu(x): return np.maximum(0, x)\ndef sigmoid(x): return 1 / (1 + np.exp(-x))\n\n# Forward pass\nX = np.array([0.5, -0.3, 0.8])\nW = np.array([0.4, 0.7, -0.2])\nb = 0.1\nz = np.dot(W, X) + b\na = relu(z)\nprint(f'Activation: {a:.4f}')", "practice_task": "Using only NumPy, implement a perceptron that learns the logical AND gate through gradient descent. Train for 100 epochs and plot loss."},
            {"title": "Backpropagation", "theory": "Backpropagation computes gradients of the loss with respect to each weight using the chain rule. These gradients update weights via gradient descent. It is the core training algorithm for all neural networks.", "video_url": "https://www.youtube.com/watch?v=Ilg3gGewQ5U", "doc_url": "https://www.geeksforgeeks.org/backpropagation-in-neural-network/", "code_example": "# Backprop for single neuron\ndef train_step(X, y, w, b, lr=0.01):\n    # Forward\n    z = np.dot(w, X) + b\n    y_hat = sigmoid(z)\n    loss = -y * np.log(y_hat) - (1-y) * np.log(1-y_hat)\n    # Backward\n    dz = y_hat - y\n    dw = dz * X\n    db = dz\n    # Update\n    w -= lr * dw\n    b -= lr * db\n    return w, b, loss", "practice_task": "Implement a 2-layer neural network from scratch using NumPy for binary classification on the XOR problem."},
            {"title": "Gradient Descent Variants", "theory": "Batch GD: uses all data per step — slow but stable.\nStochastic GD (SGD): one sample per step — fast but noisy.\nMini-batch GD: best of both.\nAdam optimizer: adaptive learning rates, widely used in practice.", "video_url": "https://www.youtube.com/watch?v=IHZwWFHWa-w", "doc_url": "https://www.geeksforgeeks.org/gradient-descent-algorithm-and-its-variants/", "code_example": "# SGD with momentum\ndef sgd_momentum(w, grad, velocity, lr=0.01, momentum=0.9):\n    velocity = momentum * velocity - lr * grad\n    w = w + velocity\n    return w, velocity\n\n# Adam optimizer update rule\ndef adam(w, grad, m, v, t, lr=0.001, b1=0.9, b2=0.999, eps=1e-8):\n    m = b1 * m + (1 - b1) * grad\n    v = b2 * v + (1 - b2) * grad**2\n    m_hat = m / (1 - b1**t)\n    v_hat = v / (1 - b2**t)\n    w -= lr * m_hat / (np.sqrt(v_hat) + eps)\n    return w, m, v", "practice_task": "Compare SGD, SGD with Momentum, and Adam on training a simple neural network. Plot their loss curves on the same graph."},
        ]},
        {"title": "Convolutional Neural Networks", "order": 4, "completed": 0, "topics": [
            {"title": "Convolution Operations", "theory": "A convolution applies a filter/kernel across an input image to detect features (edges, textures, shapes). Reduces parameters vs fully connected layers. Key parameters: kernel size, stride, padding.", "video_url": "https://www.youtube.com/watch?v=KuXjwB4LzSA", "doc_url": "https://cs231n.github.io/convolutional-networks/", "code_example": "import numpy as np\n\ndef convolve2d(input, kernel):\n    kH, kW = kernel.shape\n    iH, iW = input.shape\n    oH, oW = iH - kH + 1, iW - kW + 1\n    output = np.zeros((oH, oW))\n    for i in range(oH):\n        for j in range(oW):\n            output[i,j] = np.sum(input[i:i+kH, j:j+kW] * kernel)\n    return output", "practice_task": "Apply a Sobel edge detection kernel manually to a grayscale image using convolution. Visualize the result."},
            {"title": "Transfer Learning", "theory": "Transfer Learning reuses a model trained on a large dataset (e.g., ImageNet) for a new task. Only the final layers are retrained. Dramatically reduces training time and data requirements.", "video_url": "https://www.youtube.com/watch?v=yofjFQddwHE", "doc_url": "https://www.tensorflow.org/tutorials/images/transfer_learning", "code_example": "from tensorflow.keras.applications import MobileNetV2\nfrom tensorflow.keras import layers, models\n\nbase = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224,224,3))\nbase.trainable = False  # Freeze base\n\nmodel = models.Sequential([\n    base,\n    layers.GlobalAveragePooling2D(),\n    layers.Dense(128, activation='relu'),\n    layers.Dense(2, activation='softmax')  # 2 classes\n])\nmodel.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])", "practice_task": "Use MobileNetV2 with transfer learning to classify 2 custom image categories (e.g. cats vs dogs). Achieve >90% validation accuracy."},
        ]},
        {"title": "Natural Language Processing", "order": 5, "completed": 0, "topics": [
            {"title": "Text Preprocessing", "theory": "NLP pipeline: Tokenization → Lowercasing → Stop word removal → Stemming/Lemmatization → Vectorization (Bag of Words, TF-IDF).", "video_url": "https://www.youtube.com/watch?v=X2vAabgKiuM", "doc_url": "https://www.nltk.org/", "code_example": "import nltk\nfrom nltk.tokenize import word_tokenize\nfrom nltk.corpus import stopwords\nfrom nltk.stem import PorterStemmer\n\ntext = 'The students are studying AI algorithms'\ntokens = word_tokenize(text.lower())\nstops = set(stopwords.words('english'))\nfiltered = [t for t in tokens if t not in stops]\nstemmer = PorterStemmer()\nstemmed = [stemmer.stem(t) for t in filtered]\nprint(stemmed)", "practice_task": "Build a text classifier using TF-IDF + Logistic Regression to classify news articles into 4 categories. Report accuracy and F1 score."},
            {"title": "Transformers & BERT", "theory": "Transformers use self-attention to process entire sequences in parallel (no RNN). BERT (Bidirectional Encoder Representations from Transformers) is pre-trained on massive text and fine-tuned for tasks like QA, sentiment analysis, and NER.", "video_url": "https://www.youtube.com/watch?v=4Bdc55j80l8", "doc_url": "https://huggingface.co/docs/transformers/index", "code_example": "from transformers import pipeline\n\n# Zero-shot classification with BERT\nclassifier = pipeline('sentiment-analysis')\nresult = classifier('I absolutely love this campus AI system!')\nprint(result)\n# [{'label': 'POSITIVE', 'score': 0.9998}]", "practice_task": "Fine-tune a pre-trained BERT model on a custom dataset of 500+ student forum posts to classify sentiment (positive/negative/neutral)."},
        ]},
    ]
}

UID_DATA = {
    "title": "User Interface Design", "tag": "DES201", "progress": 0.85, "next_module": "Figma Prototyping",
    "modules": [
        {"title": "Principles of Design", "order": 0, "completed": 1, "topics": [
            {"title": "Nielsen's 10 Usability Heuristics", "theory": "Jakob Nielsen's heuristics:\n1. Visibility of system status\n2. Match between system and real world\n3. User control and freedom\n4. Consistency and standards\n5. Error prevention\n6. Recognition rather than recall\n7. Flexibility and efficiency of use\n8. Aesthetic and minimalist design\n9. Help users recognize and recover from errors\n10. Help and documentation", "video_url": "https://www.youtube.com/watch?v=6Bw0n6Jvwxk", "doc_url": "https://www.nngroup.com/articles/ten-usability-heuristics/", "code_example": "// Heuristic #5 — Error Prevention\n// BAD: Let user type date freely\nTextField(hintText: 'Enter date')\n\n// GOOD: Use a date picker to prevent invalid dates\nElevatedButton(\n  onPressed: () => showDatePicker(context: context, ...),\n  child: Text('Select Date'),\n)", "practice_task": "Evaluate Instagram against all 10 heuristics. Document 1 violation and 1 good example per heuristic with screenshots."},
            {"title": "Gestalt Principles", "theory": "Gestalt principles explain how humans perceive visual elements as organized patterns:\n- Proximity: nearby elements appear related\n- Similarity: similar elements are grouped\n- Closure: we complete incomplete shapes\n- Continuity: we follow smooth paths\n- Figure/Ground: foreground vs background distinction", "video_url": "https://www.youtube.com/watch?v=NaFKCANb0Jc", "doc_url": "https://www.nngroup.com/articles/gestalt-principles-for-design/", "code_example": "// Using Proximity and Similarity in Flutter\nRow(children: [\n  Icon(Icons.home),           // group 1\n  Icon(Icons.explore),         // group 1\n  SizedBox(width: 32),         // visual gap\n  Icon(Icons.notifications),   // group 2\n  Icon(Icons.account_circle),  // group 2\n])", "practice_task": "Design a card component layout that demonstrates all 5 Gestalt principles. Annotate each principle in your design."},
            {"title": "Visual Hierarchy & Accessibility", "theory": "Visual hierarchy guides users through content by size, color, contrast, and whitespace. Accessibility (WCAG 2.1) ensures designs work for everyone:\n- AA level: 4.5:1 contrast ratio for normal text\n- AAA level: 7:1 contrast ratio\n- Minimum touch target: 44×44 points", "video_url": "https://www.youtube.com/watch?v=qZaQ3IOQQdM", "doc_url": "https://www.w3.org/WAI/standards-guidelines/wcag/", "code_example": "// Semantic accessibility in Flutter\nSemanticsWidget(\n  label: 'Submit application form',\n  button: true,\n  child: ElevatedButton(\n    onPressed: submit,\n    child: Text('Submit', // 18sp bold = AA compliant\n      style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),\n  ),\n)", "practice_task": "Audit your own app design using the WCAG contrast checker. Fix any contrast violations and document your changes."},
        ]},
        {"title": "Color Theory & Typography", "order": 1, "completed": 1, "topics": [
            {"title": "Color Models & Psychology", "theory": "Color models: RGB (digital screens), HEX (#RRGGBB), HSL (Hue, Saturation, Lightness — most intuitive for design).\nColor psychology: Blue = trust, Red = urgency, Green = success, Yellow = caution, Purple = premium.", "video_url": "https://www.youtube.com/watch?v=AvgCkHrcj8w", "doc_url": "https://www.interaction-design.org/literature/topics/color-theory", "code_example": "// HSL color palette in Flutter (more intuitive than HEX)\nconst primaryColor = Color.fromARGB(255, 160, 82, 45);  // Sienna\nconst successColor = Color.fromARGB(255, 72, 199, 116);  // Green\nconst warningColor = Color.fromARGB(255, 255, 189, 0);   // Amber\nconst errorColor   = Color.fromARGB(255, 255, 71, 87);   // Red", "practice_task": "Create a full color palette for a fintech app (primary, secondary, success, warning, error, neutral) and justify each color choice psychologically."},
            {"title": "Typography Fundamentals", "theory": "Typography impacts readability and brand perception.\nKey concepts:\n- Type scale: 12/14/16/20/24/32/48sp hierarchy\n- Line height: 1.4-1.8× font size for body text\n- Letter spacing: -0.5px for headings, +0.5px for buttons/captions\n- Max line length: 50-75 characters for optimal readability", "video_url": "https://www.youtube.com/watch?v=QrNi9FmdlxY", "doc_url": "https://fonts.google.com/knowledge", "code_example": "// Material 3 type scale in Flutter\nTheme(\n  data: ThemeData(\n    textTheme: TextTheme(\n      displayLarge:  TextStyle(fontSize: 57, fontWeight: FontWeight.w400),\n      headlineLarge: TextStyle(fontSize: 32, fontWeight: FontWeight.w400),\n      bodyLarge:     TextStyle(fontSize: 16, fontWeight: FontWeight.w400, height: 1.5),\n      labelLarge:    TextStyle(fontSize: 14, fontWeight: FontWeight.w500, letterSpacing: 0.1),\n    ),\n  ),\n)", "practice_task": "Design a typographic hierarchy for a news app: article title, byline, publish date, body text, and caption. Use only 2 font families maximum."},
        ]},
        {"title": "User Research", "order": 2, "completed": 1, "topics": [
            {"title": "User Interviews & Personas", "theory": "User interviews uncover motivations, pain points, and mental models. Conduct 5-8 interviews to reach information saturation.\nPersonas are fictional characters representing user types, built from interview data. Include: demographics, goals, frustrations, and behaviors.", "video_url": "https://www.youtube.com/watch?v=MT4Ig2uqjTc", "doc_url": "https://www.nngroup.com/articles/user-interviews/", "code_example": "// Persona example structure\n{\n  'name': 'Priya S.',\n  'age': 21,\n  'role': 'Computer Science Student',\n  'goal': 'Track assignments and attendance without switching 5 different apps',\n  'frustration': 'University portal is slow and mobile-unfriendly',\n  'tech_comfort': 'High — uses 8+ apps daily'\n}", "practice_task": "Conduct 3 user interviews about a university study scheduling app. Synthesize findings into 2 detailed personas."},
            {"title": "User Journey Mapping", "theory": "A User Journey Map visualizes the end-to-end experience of a user accomplishing a goal. It includes: Stages → Actions → Thoughts → Emotions → Pain Points → Opportunities.", "video_url": "https://www.youtube.com/watch?v=mSxpVRo3BLg", "doc_url": "https://www.nngroup.com/articles/journey-mapping-101/", "code_example": "// Journey stage structure\n{\n  'stage': 'Discovering the App',\n  'action': 'Searches app store for study helper',\n  'thought': \"I hope this is better than the ones I've tried\",\n  'emotion': 'Hopeful but skeptical',\n  'pain_point': 'Too many options, hard to compare',\n  'opportunity': 'Feature comparison landing page'\n}", "practice_task": "Map the journey of a student who marks attendance using your face recognition feature. Identify 3 friction points and propose solutions for each."},
        ]},
        {"title": "Wireframing", "order": 3, "completed": 1, "topics": [
            {"title": "Low to High Fidelity Wireframes", "theory": "Fidelity spectrum:\n- Lo-fi: paper sketches, focus on layout/structure\n- Mid-fi: digital grayscale mockups (Figma), focused on spacing/hierarchy\n- Hi-fi: pixel-perfect with colors, typography, real content — used for development handoff", "video_url": "https://www.youtube.com/watch?v=LxTvsudxPFI", "doc_url": "https://www.figma.com/resource-library/what-is-wireframing/", "code_example": "// Lo-fi wireframe annotation (pseudocode)\nScreen: Student Home\n├── [HEADER] Logo + Notification Bell\n├── [CARD] Today's Attendance Status\n├── [GRID 2x2] Quick Actions\n│    ├── Mark Attendance\n│    ├── View Syllabus\n│    ├── AI Tutor\n│    └── Dashboard\n└── [LIST] Recent Activity", "practice_task": "Create lo-fi wireframes for 5 screens of your attendance app on paper. Then digitize them as mid-fi wireframes in Figma."},
            {"title": "Information Architecture", "theory": "Information Architecture (IA) organizes content so users can find what they need. Tools: sitemap (how pages connect), card sorting (user-driven content grouping), tree testing (navigation validation).", "video_url": "https://www.youtube.com/watch?v=Ij4WquJaRTc", "doc_url": "https://www.nngroup.com/articles/information-architecture-defined/", "code_example": "// App Sitemap (text representation)\nEduSmart App\n├── Auth\n│    ├── Login\n│    └── Register\n├── Main (Bottom Tabs)\n│    ├── Home\n│    ├── Syllabus → Module → Topic Detail\n│    ├── AI Tutor\n│    ├── Dashboard\n│    └── Profile\n│         ├── Edit Profile\n│         └── Register Face", "practice_task": "Conduct a card sorting exercise with 5 people for a university app. Group 20 feature cards into categories. Build a sitemap from results."},
        ]},
        {"title": "Figma Prototyping", "order": 4, "completed": 0, "topics": [
            {"title": "Interactive Prototypes", "theory": "Figma prototype workflow: Design screens → Add interactions (onclick → navigate to Frame) → Set transitions (Smart Animate/Slide) → Share link for user testing.\nSmart Animate works when matching layers exist — creates smooth motion.", "video_url": "https://www.youtube.com/watch?v=lTIeZ2ahEkQ", "doc_url": "https://help.figma.com/hc/en-us/articles/360040314193-Guide-to-prototyping-in-Figma", "code_example": "// Figma Interaction Config\nTrigger:   On Click\nAction:    Navigate to → [Course Detail Screen]\nAnimation: Smart Animate\nDuration:  300ms\nEasing:    Ease Out (cubic-bezier 0.4, 0, 0.2, 1)\n\n// For bottom sheet:\nTrigger:   On Click\nAction:    Open Overlay → [Bottom Sheet]\nPosition:  Bottom\nAnimation: Slide in from bottom", "practice_task": "Build a 7-screen prototype in Figma for your EduSmart app. Include: splash, login, home, syllabus, topic detail, attendance, and profile. Add 10+ interactions."},
            {"title": "Auto Layout & Components", "theory": "Auto Layout in Figma is like Flexbox — frames that resize automatically. Components are reusable design elements. Variants allow multiple states (default, hover, pressed, disabled) in one component.\nThese are the building blocks of a design system.", "video_url": "https://www.youtube.com/watch?v=TyaGpGDFczw", "doc_url": "https://help.figma.com/hc/en-us/articles/5731482952599-Using-auto-layout", "code_example": "// Button component with variants\nComponent: PrimaryButton\n  Variant: Default\n    → Fill: #A05228, Text: White, Padding: 16/32\n  Variant: Hover\n    → Fill: #8B4513 (10% darker)\n  Variant: Disabled\n    → Fill: #E0E0E0, Text: #9E9E9E, Opacity: 80%", "practice_task": "Build a complete Design System in Figma with: 10 components (buttons, inputs, cards, chips, badges), a color palette, and a typography scale."},
        ]},
        {"title": "Usability Testing", "order": 5, "completed": 0, "topics": [
            {"title": "Types of Usability Tests", "theory": "Moderated: researcher guides participant, gathers rich qualitative data but time-intensive.\nUnmoderated: participant completes tasks alone, scales to many users.\nA/B Testing: two versions shown to different users, measured quantitatively.\nGuerrilla: quick hallway testing with 5 random people.", "video_url": "https://www.youtube.com/watch?v=0YL0xoSmyZI", "doc_url": "https://www.nngroup.com/articles/usability-testing-101/", "code_example": "// Usability Test Task Script\nTask 1: 'Without any help, find and mark your attendance.'\n  → Success criteria: Completes in < 30 seconds\n  → Metric: Task completion rate\n\nTask 2: 'Find the Binary Search Trees topic and open its video.'\n  → Success criteria: Reaches YouTube link\n  → Metric: Number of clicks, time on task", "practice_task": "Run a guerrilla usability test of your EduSmart app with 5 students. Document 3 usability issues and prioritize them by severity."},
            {"title": "Iterative Design Process", "theory": "Design is never 'done.' The process cycles: Research → Define → Ideate → Prototype → Test → Iterate.\nEach cycle reduces risk. Test early with lo-fi prototypes to catch fundamental flaws before expensive development.", "video_url": "https://www.youtube.com/watch?v=a7sEoEvT8l8", "doc_url": "https://www.interaction-design.org/literature/topics/design-thinking", "code_example": "// Design Sprint timeline\nDay 1: UNDERSTAND — Map the problem, HMW notes\nDay 2: DIVERGE — Crazy 8s, solution sketches\nDay 3: DECIDE — Dot voting, storyboard\nDay 4: PROTOTYPE — Hi-fi Figma screens\nDay 5: TEST — 5 user interviews, synthesize findings", "practice_task": "Run a mini 3-day Design Sprint for one new feature of EduSmart. Sketch 8 ideas in 8 minutes (Crazy 8s), prototype the best one in Figma, and test with 3 users."},
        ]},
    ]
}


def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()

    db.query(Topic).delete()
    db.query(SyllabusModule).delete()
    db.query(Subject).delete()
    db.commit()

    for course_data in [DSA_DATA, AI_DATA, UID_DATA]:
        subj = Subject(
            title=course_data["title"],
            tag=course_data["tag"],
            progress=course_data["progress"],
            next_module=course_data["next_module"],
        )
        db.add(subj)
        db.flush()

        for m in course_data["modules"]:
            mod = SyllabusModule(
                subject_id=subj.id,
                title=m["title"],
                order_index=m["order"],
                is_completed=m["completed"],
            )
            db.add(mod)
            db.flush()

            for t in m["topics"]:
                db.add(Topic(
                    module_id=mod.id,
                    title=t["title"],
                    theory=t.get("theory"),
                    video_url=t.get("video_url"),
                    doc_url=t.get("doc_url"),
                    code_example=t.get("code_example"),
                    practice_task=t.get("practice_task"),
                ))

    db.commit()
    db.close()
    print("✅ Full syllabus seeded successfully!")
    print(f"   • DS&A: {len(DSA_DATA['modules'])} modules, {sum(len(m['topics']) for m in DSA_DATA['modules'])} topics")
    print(f"   • AI:   {len(AI_DATA['modules'])} modules, {sum(len(m['topics']) for m in AI_DATA['modules'])} topics")
    print(f"   • UID:  {len(UID_DATA['modules'])} modules, {sum(len(m['topics']) for m in UID_DATA['modules'])} topics")


if __name__ == "__main__":
    seed()
